# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Rpixpack, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Rpixpack__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Rpixpack__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Encode a string into a PixPack PNG at given path or decode an existing PixPack PNG to string.
#' If `png_path` already exists and is a PixPack PNG, it is decoded; otherwise `input` is encoded to that PNG path.
#'
#' @param input Character scalar (content when encoding; ignored on decode).
#' @param png_path Target PNG path (must be provided).
#' @return On encode: PNG path; On decode: decoded UTF-8 string (lossy).
#' @export
`StringConversion` <- function(`input`, `png_path`) {
  .Call(savvy_StringConversion__impl, `input`, `png_path`)
}

#' Encode a file to PixPack PNG or decode a PixPack PNG back to original file.
#'
#' @param path Input file path (character scalar).
#' @return Output artifact path (character scalar).
#' @export
`fileConversion` <- function(`path`) {
  .Call(savvy_fileConversion__impl, `path`)
}


